/datum/controller/global_vars/Initialize(mapload)
	. = ..()
	roguetraits[TRAIT_ALDERMAN] = span_info("Alderman of the Assembly, voice of the respectable citizenry of Pharos. Upon my charter I may spend the Crown's Purse and commission the realm's defense within the bounds the Commons have set me.")
	roguetraits[TRAIT_UNDIVIDED] = span_info("I have seen past petty squabbles, and am a true follower of the Blessed Pentacle. I feel most comfortable around the clergy.")
	roguetraits[TRAIT_GUARDSMAN] = span_info("I am vigilant in my duties. In the town of Pharos, my abilities are sharper due to my routine and familiarity.")
	roguetraits[TRAIT_WOODSMAN] = span_info("I am vigilant in my duties. In the grove and coast of Pharos, my abilities are sharper due to my routine and familiarity.")
	roguetraits[TRAIT_CLERGY] = span_info("I serve the Temple of the Pantheon in Pharos. From a passing glance, I can recognize all other clergy of this sect.")
	roguetraits[TRAIT_RESIDENT] = span_info("I've been granted a Meister account, and the ownership of a house in the Pharos.")
	roguetraits[TRAIT_DEBTOR_CHURCH] = span_danger("My defaulted debt is owed to the Temple. The faithful keep the tally.")
	roguetraits[TRAIT_AGENT_MERCHANT] = span_info("I am a chartered agent of the Pharovian Trading Company. I keep its tally and ledger.")
	roguetraits[TRAIT_AGENT_CHURCH] = span_info("I am a Benefactor of the Temple of the Pantheon. The faithful know my name.")
	roguetraits[TRAIT_HERESIARCH] = span_warning("I've been touched by the truth of Psydonia. Lyfe as we understand cannot persist under the Pentacle or the pretense of Psydon. Something must change.")
	roguetraits[TRAIT_BLACKOAK] = span_warning("The Black Oaks can spot <b>any</b> foreigners and outsiders, no matter how long they've lived in the Pharos. I can spot an invader at a glance.")
