/datum/economic_region/kingsfield
	subtitle = "The Royal Demesne, Heartland of the Kingdom"
	description = "The royal demesne of His Majesty. A stretch of land a few day's ride from the edge of Pharos, home to dozens of agricultural settlements, hamlets, and smaller market towns. Its lands are rich, and its people aplenty. The agricultural heartland of the Kingdom, producing most of its grain, meat, and dairy, imported into Pharos daily and re-exported for profit. Many of the nobles across the kingdom keep one estate here or another - though its courts are best compared to a pit of snakes."

/datum/economic_region/rosawood
	description = "The last vassal of the Kingdom still ruled by an elven lord with a majority elven population. An elven enclave on a peninsula jutting north of Mount Decapitation, alongside a narrow strip of infertile coastal woodland known as the Southern Rosawood. Access is largely by sea. Lumber is exported from the southern edge. The county is unusually, almost magically cold, its growing season barely three months a yil. Its inhabitants feed themselves on those three months of harvest, supplemented by fish from the northern sea, though it never produces or exports enough to supply the Kingdom. The overland route through the passes below Decapitation is passable, but slow, and fraught with rogue Black Oaks. And the elves prefer it that way. Some say, the beautiful white cloaks of the Rosawood Count, are woven in the same manner as those of the Black Oaks, notorious mercenaries that are barely tolerated the Crown. As for any allegations of collusion, the Count of Rosawood has always been quick to deny them, and the Crown has never found any evidence to the contrary."

/datum/economic_region/rockhill
	description = "A cluster of orchards and herb gardens to the north of the Pharos, sheltered by a ridge that makes the climate there milder than it has any right to be. The many rolling hills of the county make for poor grain land but excellent orchard land. Rockhill wine and liquor are renowned throughout Azuria, and some are exported beyond. It is a quiet, quaint, agricultural county, dotted with noble estates. Rockhill apple brandy is the realm's most counterfeited drink. Every other inn from Bleakcoast to Heartfelt claims to serve it, but perhaps only a third of them actually do. The county is also known for its many country manor, with perhaps three quarter of the noble houses of the realm owning at least one in Rockhill."

/datum/economic_region/daftsmarch
	description = "The County of Daftsmarch is the heart of the Kingdom's mining industry, a long strip of land hugging the southern end of Mount Decapitation. It produces most of the raw ore and salt that the Kingdom depends on. The work pays well, and the veins are plentiful. But Daftsmarch sits uncomfortably close to the ruins of Tarichea, and the various denizens of the Underdark. The dangers posed by the drows and their ilk are a constant threat - many of them seeing Daftsmarch as a convenient source of slaves. But the ore vein are even richer - and the Crown is loathe to keep them unused - sending adventurers, mercenaries and garrison alike to do battle with the Underdark's denizens and keep them at bay."

/datum/economic_region/blackholt
	description = "A settlement at the southern edge of the Terrorbog, part of the Royal Demesne, and the only part the King never tours or manages directly. Instead, management is assigned to a special courtier, the Huntsmarshal of Blackholt. It straddles the bog proper and the undrained marshland at its edge. The locals have learned to make a living off the bog's unusual, some say Psydon-blessed yields: silk from its moths, viscera from its inhabitants, and the rare Essence of Dendor that herbalists and mages pay handsomely for. Blackholt itself is a grim, functional place. Nobody moves there. People end up there."

/datum/economic_region/saltwick
	description = "A settlement southeast of Pharos, around a day's ride away, located on the coast of Kingsfield. It was settled first by immigrants from Hammerhold and later by settlers from southern Gronn. The town is divided starkly into two parts: The curing houses and salt farms owned mostly by the town's dwarven and Hammerheldan settlers, while those of Gronnic descent makes up most of the fishermen and sailors. The two groups marry eachother rarely and argue often - but coexists somewhat harmoniously in the same town either way. Of course, Hammerheldan and Gronnmen are not the only inhabitants - many people down on their luck or seeking work also reside. Salt is imported from Daftsmarch, used to preserve the fish caught by local fishermen, and then exported throughout the Kingdom and Psydonia."

/datum/economic_region/bleakcoast
	description = "Also known as the Bleakisles Seamarch. A series of rocky outcrops said to have been created in the tumultuous reign of the Demiurge; when the Scar was still yet a Wound. Violently shaping and unshaping the seas and coasts around it, a cacaphonous eruption radiated outward and hurling the islands from the sea itself. The archipelago numbers in the hundreds and makes navigation along all but a narrow stretch of the Kingdom's coast treacherous. What it lacks in fertile land it makes up for in the bounty of its seas. Schools of fish swarm in the shallow, rocky bottoms and swim as far as the Kingdom's coast, feeding thousands. But that bounty is not for Bleakisles inhabitants to enjoy. The isles are infested with pirates, the notorious Bleakisles Reavers, who prey on any merchant or fisherman that strays too far from shore. The King maintains several garrisons to keep them in check, and has, once every two generations, undertaken a harrying of the isles, burning every non-military settlement and salting it. To no avail. Within a generation, the pirates always return, for trade is lucrative, and piracy even more so."

/datum/economic_region/northfort
	description = "A fortified castle at the northern approach into the Kingdom, the only direct overland route from the north. As economically unproductive as a fort can be, which is very. The crown feeds it because without it, the border between Grenzelhoft and the Kingdom becomes negotiable."

/datum/economic_region/heartfelt
	subtitle = "The Bloody Barony of the Border"
	description = "The County of Heartfelt is the Pharos' closest court, comprising nearly the entirety of the western borderland, bordering Otava, Grenzelhoft, Naledi, and Aavnr. The Count of Heartfelt has always been afforded considerable liberty in how they raise revenues and how many men they keep under arms, for if Heartfelt falls, His Majesty's heartland would be exposed. Its defense is funded by a network of estates, holdings, and acres scattered across hundreds of pockets in the Kingdom outside Heartfelt proper, which the Baron uses to purchase armaments and pay retinue alike. But any ruler within Pharos knows there is no greater threat to themselves than the self-professed greatest defender of the Kingdom."

/datum/economic_region/hagenwald
	description = "The industrial heart of the Kingdom, sitting on the northern face of Mount Decapitation, where Daftsmarch's ore is taken by mules to be smelted, refined, and forged. Hagenwald produces nearly every ingot of iron, steel, copper, and tin the kingdom uses - without its furnaces, the Kingdom's smiths would be reduced to working scrap. The town's wealth is built on coppiced woodland that flanks it on three sides, cut and re-cut on a generational rotation so the fire never go out. Its workforce is half Grenzelhoftian by descent, drawn over the centuries by wages, and the streets are perpetually grey with soot. The Crown garrisons it quietly."
